/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: deep.dubb (https://sketchfab.com/deep.dubb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/edificio-con-giardino-low-poly-90efc91bba5b42208787f6de0cd560a2
Title: Edificio con giardino Low Poly
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from '@react-spring/three'

import Scene from '../assets/3d/edificio.glb'

const Edificio = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
    const edificioRef = useRef()

    const { gl, viewport } = useThree()
    const { nodes, materials } = useGLTF(Scene);

    const lastX = useRef(0);
    const rotationSpeed = useRef(0)
    const dampingFactor = 0.95;

    const handlePointerDown = (e) => {
        e.stopPropagation()
        e.preventDefault()
        setIsRotating(true)

        const clientX = e.touches
            ? e.touches[0] - clientX
            : e.clientX;

        lastX.current = clientX
    }

    const handlePointerUp = (e) => {
        e.stopPropagation()
        e.preventDefault()
        setIsRotating(false)

    }

    const handlePointerMove = (e) => {
        e.stopPropagation()
        e.preventDefault()

        if (isRotating) {
            const clientX = e.touches
                ? e.touches[0] - clientX
                : e.clientX;

            const delta = (clientX - lastX.current) / viewport.width;

            edificioRef.current.rotation.y += delta * 0.01 * Math.PI;
            lastX.current = clientX;
            rotationSpeed.current = delta * 0.01 * Math.PI;


        }




    }

    const handleKeyDown = () => {
        if (e.key === 'ArrowLeft') {
            if (!isRotating) setIsRotating(true);
            castleRef.current.rotation.y += 0.01 * Math.PI
        } else if (e.key === 'ArrowRight') {
            if (!isRotating) setIsRotating(true)
            castleRef.current.rotation.y -= 0.01 * Math.PI
        }

    }

    const handleKeyUp = (e) => {
        if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
            setIsRotating(false)
        }
    }

    useFrame(() => {
        if (!isRotating) {
            rotationSpeed.current *= dampingFactor

            if (Math.abs(rotationSpeed.current) < 0.001) {
                rotationSpeed.current = 0
            }

            edificioRef.current.rotation.y += rotationSpeed.current
        } else {
            const rotation = edificioRef.current.rotation.y

            const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI)

            //setea el actual estado basado en la orientacion del castillo

            switch (true) {
                case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
                    setCurrentStage(4)
                    break;
                case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
                    setCurrentStage(3)
                    break;
                case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
                    setCurrentStage(2)
                    break;
                case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
                    setCurrentStage(1)
                    break;


                default:
                    break;
            }
        }
    })

    useEffect(() => {
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handlePointerDown)
        canvas.addEventListener('pointerup', handlePointerUp)
        canvas.addEventListener('pointermove', handlePointerMove)
        document.addEventListener('keydown', handleKeyDown)
        document.addEventListener('keyup', handleKeyUp)

        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown)
            canvas.removeEventListener('pointerup', handlePointerUp)
            canvas.removeEventListener('pointermove', handlePointerMove)
            document.removeEventListener('keydown', handleKeyDown)
            document.removeEventListener('keyup', handleKeyUp)
        }


    }, [gl, handlePointerDown, handlePointerMove, handlePointerUp])

    return (
        <a.group {...props} ref={edificioRef}>
            <group
                position={[-69.429, -38.874, 143.768]}
                rotation={[-1.574, -0.022, -0.212]}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-349.777, 10.785, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.CASA003_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.CASA003_Finestre_0.geometry}
                            material={materials.Finestre}
                        />
                    </group>
                    <group
                        position={[-889.65, 92, -1114.033]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.CASA004_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.CASA004_Finestre_0.geometry}
                            material={materials.Finestre}
                        />
                    </group>
                    <group
                        position={[208.687, 81.711, -916.241]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1007_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere031_Material_0.geometry}
                            material={materials.Material}
                            position={[0.027, 0.043, 0.947]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere032_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.552, -0.498, 0.686]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere033_Material_0.geometry}
                            material={materials.Material}
                            position={[0.642, -0.085, 0.623]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere034_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.417, 0.556, 0.3]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere035_Material_0.geometry}
                            material={materials.Material}
                            position={[0.128, 0.595, 0.263]}
                            rotation={[0, 0, 2.245]}
                        />
                    </group>
                    <group
                        position={[-4.468, 94.279, -916.241]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1008_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere036_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.042, 0.51, 0.979]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere037_Material_0.geometry}
                            material={materials.Material}
                            position={[0.647, -0.021, 0.51]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere038_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.704, -0.199, 0.644]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere039_Material_0.geometry}
                            material={materials.Material}
                            position={[0.446, -0.467, 0.429]}
                            scale={[1, 1, 1.128]}
                        />
                    </group>
                    <group
                        position={[-231.192, 94.279, -916.241]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1009_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere040_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.48, -0.177, 0.979]}
                            rotation={[0, 0, 1.842]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere041_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.153, 0.629, 0.51]}
                            rotation={[0, 0, 1.842]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere042_Material_0.geometry}
                            material={materials.Material}
                            position={[0.38, -0.624, 0.644]}
                            rotation={[0, 0, 1.842]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere043_Material_0.geometry}
                            material={materials.Material}
                            position={[0.33, 0.555, 0.429]}
                            rotation={[0, 0, 1.842]}
                            scale={[1, 1, 1.128]}
                        />
                    </group>
                    <group
                        position={[-889.5, 632, -1067.496]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.CASA005_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.CASA005_Finestre_0.geometry}
                            material={materials.Finestre}
                        />
                    </group>
                    <group
                        position={[-869.314, 81.711, -1490.651]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1010_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere044_Material_0.geometry}
                            material={materials.Material}
                            position={[0.027, 0.043, 0.947]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere045_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.552, -0.498, 0.686]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere046_Material_0.geometry}
                            material={materials.Material}
                            position={[0.642, -0.085, 0.623]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere047_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.417, 0.556, 0.3]}
                            rotation={[0, 0, 2.245]}
                        />
                        <mesh


                            geometry={nodes.Icosphere048_Material_0.geometry}
                            material={materials.Material}
                            position={[0.128, 0.595, 0.263]}
                            rotation={[0, 0, 2.245]}
                        />
                    </group>
                    <group
                        position={[-1082.469, 94.279, -1490.651]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1011_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere049_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.042, 0.51, 0.979]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere050_Material_0.geometry}
                            material={materials.Material}
                            position={[0.647, -0.021, 0.51]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere051_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.704, -0.199, 0.644]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere052_Material_0.geometry}
                            material={materials.Material}
                            position={[0.446, -0.467, 0.429]}
                            scale={[1, 1, 1.128]}
                        />
                    </group>
                    <group
                        position={[-1553.829, 81.711, -1211.665]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1012_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere053_Material_0.geometry}
                            material={materials.Material}
                            position={[0.046, -0.021, 0.947]}
                            rotation={[0, 0, 0.789]}
                        />
                        <mesh


                            geometry={nodes.Icosphere054_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.558, 0.492, 0.686]}
                            rotation={[0, 0, 0.789]}
                        />
                        <mesh


                            geometry={nodes.Icosphere055_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.01, -0.648, 0.623]}
                            rotation={[0, 0, 0.789]}
                        />
                        <mesh


                            geometry={nodes.Icosphere056_Material_0.geometry}
                            material={materials.Material}
                            position={[0.505, 0.478, 0.3]}
                            rotation={[0, 0, 0.789]}
                        />
                        <mesh


                            geometry={nodes.Icosphere057_Material_0.geometry}
                            material={materials.Material}
                            position={[0.606, -0.059, 0.263]}
                            rotation={[0, 0, 0.789]}
                        />
                    </group>
                    <group
                        position={[-1578.246, 94.279, -1423.417]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <mesh


                            geometry={nodes.Albero_1013_Material_0.geometry}
                            material={materials.Material}
                        />
                        <mesh


                            geometry={nodes.Icosphere058_Material_0.geometry}
                            material={materials.Material}
                            position={[0.502, 0.1, 0.979]}
                            rotation={[0, 0, -1.456]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere059_Material_0.geometry}
                            material={materials.Material}
                            position={[0.053, -0.645, 0.51]}
                            rotation={[0, 0, -1.456]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere060_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.278, 0.676, 0.644]}
                            rotation={[0, 0, -1.456]}
                            scale={[1, 1, 1.128]}
                        />
                        <mesh


                            geometry={nodes.Icosphere061_Material_0.geometry}
                            material={materials.Material}
                            position={[-0.412, -0.497, 0.429]}
                            rotation={[0, 0, -1.456]}
                            scale={[1, 1, 1.128]}
                        />
                    </group>
                    <mesh


                        geometry={nodes.Uscita_aria003_Material_0.geometry}
                        material={materials.Material}
                        position={[-439.663, 381.069, -586.189]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Uscita_aria_02003_Material_0.geometry}
                        material={materials.Material}
                        position={[-532.669, 393.399, -585.322]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Motore_aerazione003_Material_0.geometry}
                        material={materials.Material}
                        position={[-132.078, 371.347, -569.927]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Ventola003_Material_0.geometry}
                        material={materials.Material}
                        position={[-142.61, 380.727, -569.927]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Tubo003_Material_0.geometry}
                        material={materials.Material}
                        position={[-87.523, 361.622, -552.671]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Base_01002_Material_0.geometry}
                        material={materials.Material}
                        position={[-350.443, -9, -390.023]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.BASE_CASA001_Material_0.geometry}
                        material={materials.Material}
                        position={[-619.993, -27.829, -706.484]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Scale001_Material_0.geometry}
                        material={materials.Material}
                        position={[-555.911, -8.702, 43.751]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Cube004_Material_0.geometry}
                        material={materials.Material}
                        position={[156.151, 0.514, 95.307]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Perimetro_giardino002_Material_0.geometry}
                        material={materials.Material}
                        position={[-39.802, -14.348, -379.882]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[100, 112.693, 100]}
                    />
                    <mesh


                        geometry={nodes.erba002_Material_0.geometry}
                        material={materials.Material}
                        position={[140.646, 1.456, 71.785]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Base_01003_Material_0.geometry}
                        material={materials.Material}
                        position={[-890.654, -9, -1091]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Uscita_aria004_Material_0.geometry}
                        material={materials.Material}
                        position={[-1007.221, 737.996, -1203.099]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Uscita_aria_02004_Material_0.geometry}
                        material={materials.Material}
                        position={[-1101.338, 750.326, -1202.232]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Motore_aerazione004_Material_0.geometry}
                        material={materials.Material}
                        position={[-671.135, 729.832, -1172.779]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Ventola004_Material_0.geometry}
                        material={materials.Material}
                        position={[-681.667, 739.439, -1172.779]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Tubo004_Material_0.geometry}
                        material={materials.Material}
                        position={[-626.579, 720.217, -1155.523]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Perimetro_giardino003_Material_0.geometry}
                        material={materials.Material}
                        position={[-1189.302, -14.348, -1098.608]}
                        rotation={[-Math.PI / 2, 0, Math.PI]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.Cube005_Material_0.geometry}
                        material={materials.Material}
                        position={[-1412.777, 0.514, -737.635]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh


                        geometry={nodes.erba003_Material_0.geometry}
                        material={materials.Material}
                        position={[-1428.282, 1.456, -761.157]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                </group>
            </group>
        </a.group>
    );
}



export default Edificio;

